name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
      options: --security-opt seccomp=unconfined
    steps:
    - name: Install deps and tools
      run: |
        apt-get update
        # fix git version < 2.18
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:git-core/ppa
        apt-get update
        # deps
        apt-get install -y git wget libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev tree
    - name: Install kcov
      run: |
        wget -q https://github.com/SimonKagstrom/kcov/releases/download/pre-v40/kcov-amd64.tar.gz
        tar -xzf kcov-amd64.tar.gz -C /
    - uses: actions/checkout@v2
    - name: Install crystal shards
      run: shards install
    - name: Build tests
      run: crystal build --debug spec/ipaddress_spec.cr
    - name: Run tests with coverage
      run: kcov --strip-path=$(pwd)/ --include-path=./src --coveralls-id=dry-run ./coverage ./ipaddress_spec
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      if: ${{ env.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{github.workspace}}/cover*/**/coveralls.out:excoveralls
