name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
      options: --security-opt seccomp=unconfined
    steps:
    - name: Install deps and tools
      run: |
        apt-get update
        # fix git version < 2.18
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:git-core/ppa
        apt-get update
        # deps
        apt-get install -y git wget libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev tree
    - name: Install kcov
      run: |
        wget -q https://github.com/SimonKagstrom/kcov/releases/download/pre-v40/kcov-amd64.tar.gz
        tar -xzf kcov-amd64.tar.gz -C /
    - name: Install CC test reporter tool
      run:
        wget -q https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
        chmod +x cc-test-reporter
        mv cc-test-reporter /usr/local/bin
    - uses: actions/checkout@v2
    - name: Install crystal shards
      run: shards install
    - name: Build tests
      run: crystal build --debug spec/ipaddress_spec.cr
    - name: Run tests with coverage
      run: kcov --strip-path=$(pwd)/ --include-path=./src --coveralls-id=dry-run ./coverage ./ipaddress_spec
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: a12201a359005a473a46b5392ef281e9f0ba9d2e917dd1d293d9d07ae8ecce33
      with:
        coverageLocations: |
          ${{github.workspace}}/cover*/**/coveralls.out:excoveralls
